# -*- coding: utf-8 -*-
"""Wetland_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AhH1g-ZVkh-zml77cRuINxgVZLTpj7yu
"""

import ee
import geemap
import xarray as xr

!pip install xee
import xee

ee.Authenticate()
ee.Initialize(
    project = 'ee-lavibas23',
    opt_url = 'https://earthengine-highvolume.googleapis.com'
)

import ee
import geemap

# Initialize the map
Map = geemap.Map(basemap='SATELLITE')

# Define ROI (Vankalai Wetland, Mannar District)
# roi = ee.Geometry.BBox(79.975, 8.895, 80.085, 9.005)
roi = ee.Geometry.BBox(79.92, 8.85, 80.12, 9.05)


# Center the map on ROI and add it as a red layer
Map.centerObject(roi, zoom=12)
Map.addLayer(roi, {'color': 'red'}, 'ROI - Vankalai')

# Display the map!
Map

landsat = (
    ee.ImageCollection("LANDSAT/LC08/C02/T1_L2")
    .filterDate('2020', '2024')
    .filterBounds(roi)
    .filter(ee.Filter.lt('CLOUD_COVER',45))
)

landsat

landsat_mean = landsat.select('SR_B.*').mean()
landsat_mean

ds = xr.open_dataset(
    landsat_mean,
    engine = 'ee',
    crs = 'EPSG:4326',
    scale = 0.0001,
    geometry = roi
)

ds = ds * 2.75e-05 + (-0.2)

nir = ds.SR_B5
red = ds.SR_B4
swir2 = ds.SR_B7

import matplotlib.pyplot as plt

fig, ax = plt.subplots(1,2, figsize = (10,5))
plt.tight_layout(w_pad = 4)

nir.plot(
    x = 'lon',
    y = 'lat',
    robust = True,
    ax = ax[0]
)

swir2.plot(
    x = 'lon',
    y = 'lat',
    robust = True,
    ax = ax[1]
)

ndvi = (nir - red) / (nir + red)

ndvi.plot(
    x = 'lon',
    y = 'lat',
    robust = True
)

green = ds.SR_B3

ndwi = (green - nir) / (green + nir)

ndwi.plot(
    x = 'lon',
    y = 'lat',
    robust = True
)

wiw = (nir <= 0.1735) & (swir2 <= 0.1035)

wiw.plot(
    x = 'lon',
    y = 'lat'
)

wiw = (nir <= 0.1735) | (swir2 <= 0.1035)

wiw.plot(
    x = 'lon',
    y = 'lat'
)